/**
 * Copyright (c) 2000-2010 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.lig.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Insult service. Represents a row in the &quot;insults_Insult&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.lig.model.impl.InsultModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.lig.model.impl.InsultImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a insult model instance should use the {@link Insult} interface instead.
 * </p>
 *
 * @author Rich Sezov
 * @see Insult
 * @see com.liferay.lig.model.impl.InsultImpl
 * @see com.liferay.lig.model.impl.InsultModelImpl
 * @generated
 */
public interface InsultModel extends BaseModel<Insult> {
	/**
	 * Gets the primary key of this insult.
	 *
	 * @return the primary key of this insult
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this insult
	 *
	 * @param pk the primary key of this insult
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the insult id of this insult.
	 *
	 * @return the insult id of this insult
	 */
	public long getInsultId();

	/**
	 * Sets the insult id of this insult.
	 *
	 * @param insultId the insult id of this insult
	 */
	public void setInsultId(long insultId);

	/**
	 * Gets the adjective one of this insult.
	 *
	 * @return the adjective one of this insult
	 */
	@AutoEscape
	public String getAdjectiveOne();

	/**
	 * Sets the adjective one of this insult.
	 *
	 * @param adjectiveOne the adjective one of this insult
	 */
	public void setAdjectiveOne(String adjectiveOne);

	/**
	 * Gets the direct object of this insult.
	 *
	 * @return the direct object of this insult
	 */
	@AutoEscape
	public String getDirectObject();

	/**
	 * Sets the direct object of this insult.
	 *
	 * @param directObject the direct object of this insult
	 */
	public void setDirectObject(String directObject);

	/**
	 * Gets the adjective two of this insult.
	 *
	 * @return the adjective two of this insult
	 */
	@AutoEscape
	public String getAdjectiveTwo();

	/**
	 * Sets the adjective two of this insult.
	 *
	 * @param adjectiveTwo the adjective two of this insult
	 */
	public void setAdjectiveTwo(String adjectiveTwo);

	/**
	 * Gets the obj preposition of this insult.
	 *
	 * @return the obj preposition of this insult
	 */
	@AutoEscape
	public String getObjPreposition();

	/**
	 * Sets the obj preposition of this insult.
	 *
	 * @param objPreposition the obj preposition of this insult
	 */
	public void setObjPreposition(String objPreposition);

	/**
	 * Gets the company id of this insult.
	 *
	 * @return the company id of this insult
	 */
	public long getCompanyId();

	/**
	 * Sets the company id of this insult.
	 *
	 * @param companyId the company id of this insult
	 */
	public void setCompanyId(long companyId);

	/**
	 * Gets the group id of this insult.
	 *
	 * @return the group id of this insult
	 */
	public long getGroupId();

	/**
	 * Sets the group id of this insult.
	 *
	 * @param groupId the group id of this insult
	 */
	public void setGroupId(long groupId);

	/**
	 * Gets the user id of this insult.
	 *
	 * @return the user id of this insult
	 */
	public long getUserId();

	/**
	 * Sets the user id of this insult.
	 *
	 * @param userId the user id of this insult
	 */
	public void setUserId(long userId);

	/**
	 * Gets the user uuid of this insult.
	 *
	 * @return the user uuid of this insult
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this insult.
	 *
	 * @param userUuid the user uuid of this insult
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Gets a copy of this insult as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public Insult toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Insult insult);

	public int hashCode();

	public String toString();

	public String toXmlString();
}