/**
 * Copyright (c) 2000-2010 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.lig.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.lig.model.Insult;
import com.liferay.lig.service.InsultLocalService;
import com.liferay.lig.service.InsultService;
import com.liferay.lig.service.persistence.InsultPersistence;

import com.liferay.portal.kernel.annotation.BeanReference;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the insult local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.lig.service.impl.InsultLocalServiceImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. Always use {@link com.liferay.lig.service.InsultLocalServiceUtil} to access the insult local service.
 * </p>
 *
 * @author Rich Sezov
 * @see com.liferay.lig.service.impl.InsultLocalServiceImpl
 * @see com.liferay.lig.service.InsultLocalServiceUtil
 * @generated
 */
public abstract class InsultLocalServiceBaseImpl implements InsultLocalService {
	/**
	 * Adds the insult to the database. Also notifies the appropriate model listeners.
	 *
	 * @param insult the insult to add
	 * @return the insult that was added
	 * @throws SystemException if a system exception occurred
	 */
	public Insult addInsult(Insult insult) throws SystemException {
		insult.setNew(true);

		return insultPersistence.update(insult, false);
	}

	/**
	 * Creates a new insult with the primary key. Does not add the insult to the database.
	 *
	 * @param insultId the primary key for the new insult
	 * @return the new insult
	 */
	public Insult createInsult(long insultId) {
		return insultPersistence.create(insultId);
	}

	/**
	 * Deletes the insult with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param insultId the primary key of the insult to delete
	 * @throws PortalException if a insult with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteInsult(long insultId)
		throws PortalException, SystemException {
		insultPersistence.remove(insultId);
	}

	/**
	 * Deletes the insult from the database. Also notifies the appropriate model listeners.
	 *
	 * @param insult the insult to delete
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteInsult(Insult insult)
		throws PortalException, SystemException {
		insultPersistence.remove(insult);
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return insultPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @param start the lower bound of the range of model instances to return
	 * @param end the upper bound of the range of model instances to return (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return insultPersistence.findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @param start the lower bound of the range of model instances to return
	 * @param end the upper bound of the range of model instances to return (not inclusive)
	 * @param orderByComparator the comparator to order the results by
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return insultPersistence.findWithDynamicQuery(dynamicQuery, start, end,
			orderByComparator);
	}

	/**
	 * Counts the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return insultPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Gets the insult with the primary key.
	 *
	 * @param insultId the primary key of the insult to get
	 * @return the insult
	 * @throws PortalException if a insult with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public Insult getInsult(long insultId)
		throws PortalException, SystemException {
		return insultPersistence.findByPrimaryKey(insultId);
	}

	/**
	 * Gets a range of all the insults.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of insults to return
	 * @param end the upper bound of the range of insults to return (not inclusive)
	 * @return the range of insults
	 * @throws SystemException if a system exception occurred
	 */
	public List<Insult> getInsults(int start, int end)
		throws SystemException {
		return insultPersistence.findAll(start, end);
	}

	/**
	 * Gets the number of insults.
	 *
	 * @return the number of insults
	 * @throws SystemException if a system exception occurred
	 */
	public int getInsultsCount() throws SystemException {
		return insultPersistence.countAll();
	}

	/**
	 * Updates the insult in the database. Also notifies the appropriate model listeners.
	 *
	 * @param insult the insult to update
	 * @return the insult that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public Insult updateInsult(Insult insult) throws SystemException {
		insult.setNew(false);

		return insultPersistence.update(insult, true);
	}

	/**
	 * Updates the insult in the database. Also notifies the appropriate model listeners.
	 *
	 * @param insult the insult to update
	 * @param merge whether to merge the insult with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the insult that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public Insult updateInsult(Insult insult, boolean merge)
		throws SystemException {
		insult.setNew(false);

		return insultPersistence.update(insult, merge);
	}

	/**
	 * Gets the insult local service.
	 *
	 * @return the insult local service
	 */
	public InsultLocalService getInsultLocalService() {
		return insultLocalService;
	}

	/**
	 * Sets the insult local service.
	 *
	 * @param insultLocalService the insult local service
	 */
	public void setInsultLocalService(InsultLocalService insultLocalService) {
		this.insultLocalService = insultLocalService;
	}

	/**
	 * Gets the insult remote service.
	 *
	 * @return the insult remote service
	 */
	public InsultService getInsultService() {
		return insultService;
	}

	/**
	 * Sets the insult remote service.
	 *
	 * @param insultService the insult remote service
	 */
	public void setInsultService(InsultService insultService) {
		this.insultService = insultService;
	}

	/**
	 * Gets the insult persistence.
	 *
	 * @return the insult persistence
	 */
	public InsultPersistence getInsultPersistence() {
		return insultPersistence;
	}

	/**
	 * Sets the insult persistence.
	 *
	 * @param insultPersistence the insult persistence
	 */
	public void setInsultPersistence(InsultPersistence insultPersistence) {
		this.insultPersistence = insultPersistence;
	}

	/**
	 * Gets the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Gets the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Gets the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Gets the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Gets the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Gets the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Gets the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query to perform
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = insultPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = InsultLocalService.class)
	protected InsultLocalService insultLocalService;
	@BeanReference(type = InsultService.class)
	protected InsultService insultService;
	@BeanReference(type = InsultPersistence.class)
	protected InsultPersistence insultPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}